server:
  port : 8763
spring:
  application:
    name : business-one
  datasource:
   url: "jdbc:mysql://localhost:3306/business-one-db"
   driver-class-name: com.mysql.jdbc.Driver
   username: "root"
   password: "root"
  jpa:
   hibernate:
     ddl-auto: update
   generate-ddl: true
   show-sql: true
   database-platform: org.hibernate.dialect.MySQL5Dialect  
   
#eureka:
#  instance:
#    hostname: localhost
#    preferIpAddress : false
#    prefer-ip-address: true
#  client:
#    registerWithEureka : true
#    fetchRegistry : true
#  serviceUrl:
#    defaultZone : http://localhost:8761/eureka
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka